<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",103,119);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",138,223);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",253,268);
$z[3][4]=array();
$z[4]=Array("imgwidth","",282,300);
$z[4][4]=array();
$z[5]=Array("alttext","",306,323);
$z[5][4]=array();
$z[6]=Array("linkurl","",532,548);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",550,636);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("alttext","",655,672);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",710,790);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>