<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",99,115);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",117,202);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",228,243);
$z[3][4]=array();
$z[4]=Array("imgwidth","",257,275);
$z[4][4]=array();
$z[5]=Array("alttext","",281,298);
$z[5][4]=array();
$z[6]=Array("linkurl","",352,368);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",370,456);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",472,487);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",517,597);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>