<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",93,109);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",128,213);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",230,245);
$z[3][4]=array();
$z[4]=Array("imgwidth","",259,277);
$z[4][4]=array();
$z[5]=Array("alttext","",283,300);
$z[5][4]=array();
$z[6]=Array("linkurl","",479,495);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",497,583);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("alttext","",592,609);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",627,707);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>