<li class="project col-4 nested mobile-full" id="project-4">
        <a class="project-link flipped mobile-unflip" href="[field:arcurl/]" style="display: flex;">
          <div class="project-number col-2 mobile-full">
            <h3>04</h3>
            <h6 class="active">[field:typename/]</h6>
            <h2>[field:title/]</h2>
            <p>[field:description function="cutStr(@me,120)/]</p>
          </div>
          <div class="col-2 mobile-full">
            <img class="project-thumb smaller" alt="[field:title/]" src="[field:litpic/]" draggable="false" />
          </div>
        </a>
      </li>