<div class="carousel-item">
          <img src='[field:imgsrc/]' alt='[field:alttext /]' />
          <div class="carousel-caption">
            [field:alttext /]
            <div class="caption-overlay" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; flex-direction: column;">
              <div class="blurgradual" style="backdrop-filter: blur(0.4px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(0.7px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(0.8px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(1px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(1.5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(2px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(3px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(4px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(6px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(7px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(8px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(9px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(10px);"></div>

            </div>
          </div>
        </div>