<?php
$z[0]=Array("arcurl","",69,84);
$z[0][4]=array();
$z[1]=Array("global"," if(@me < 10) { @me = \"0\".@me; } ",180,275);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("title","",439,453);
$z[2][4]=array();
$z[3]=Array("litpic","",460,475);
$z[3][4]=array();
$z[4]=Array("pubdate","",591,638);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("title","",677,717);
$z[5][4]=array();
$z[5][4]['function']="cutStr(@me,60)";
$z[6]=Array("description","",755,802);
$z[6][4]=array();
$z[6][4]['function']="cutStr(@me,120)";

?>