<li class="project col-4 nested mobile-full" id="project-1">
        <div class="project-number col-1 mobile-full project-m-01"><h3>01</h3></div>
        <div class="col-3 mobile-full">
          <a class="project-link" href="[field:arcurl/]">
            <img class="project-thumb" alt="[field:title/]" src="[field:litpic/]" draggable="false" />
            <h6 class="active">[field:typename/]</h6>
            <h2><strong>[field:title/]</strong></h2>
            <p>[field:description function="cutStr(@me,120)/]</p>
          </a>
        </div>
      </li>