<?php
$z[0]=Array("pagestyle","\n			if(@me==3) {\n				@me = '<div class=\"image-container\">';\n			}\n			",0,116);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",130,146);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me=(@me==3 ? 'class=\"pic\"' : '' ); ",148,234);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",251,266);
$z[3][4]=array();
$z[4]=Array("imgwidth","",280,298);
$z[4][4]=array();
$z[5]=Array("alttext","",304,321);
$z[5][4]=array();
$z[6]=Array("linkurl","",359,375);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me=(@me==3 ? 'class=\"title\"' : '' );",377,463);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",470,485);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '\n			</li>' : ''); ",499,583);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>