<div class="carousel-item">
          <img src='[field:imgsrc/]' alt='[field:alttext /]' />
          <div class="carousel-caption">
            [field:alttext /]
            <div class="caption-overlay" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; flex-direction: column;">
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>
              <div class="blurgradual" style="backdrop-filter: blur(5px);"></div>

            </div>
          </div>
        </div>