<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/250326/1-115KJG5.jpg ",93,237);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/250326/1-115KJG5-lp.jpg";
$z[1][4]['text']="18";
$z[1][4]['width']="1742";
$z[1][4]['height']="1025";
$z[2]=Array("img"," /uploads/allimg/250326/1-115KN508.jpg ",239,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/250326/1-115KN508-lp.jpg";
$z[2][4]['text']="17";
$z[2][4]['width']="2342";
$z[2][4]['height']="1375";
$z[3]=Array("img"," /uploads/allimg/250326/1-115KK129.jpg ",387,531);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/250326/1-115KK129-lp.jpg";
$z[3][4]['text']="16";
$z[3][4]['width']="834";
$z[3][4]['height']="490";

?>