<?php
$z[0]=Array("imgsrc","\n			if(@me == '') {\n				@me = '<a href=\"[field:linkurl/]\" class=\"pic\"><img src=\"[field:litpic/]\" alt=\"[field:alttext /]\" /></a>';\n			} else {\n				@me = '<a href=\"[field:linkurl/]\" class=\"pic\"><img src=\"[field:imgsrc/]\" alt=\"[field:alttext /]\" /></a>';\n			}\n			",0,302);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",315,331);
$z[1][4]=array();
$z[2]=Array("title","",352,367);
$z[2][4]=array();

?>