<?php
$z[0]=Array("imgsrc","\n            if(@me) {\n                @me = '<div class=\"image-container\">';\n                @me .= '<img class=\"image project-header\" alt=\"[field:alttext /]\" src=\"[field:imgsrc/]\" />';\n                @me .= '</div>';\n            } else {\n                @me = '<div class=\"image-container\">';\n                @me .= '<img class=\"image project-header\" alt=\"[field:title /]\" src=\"[field:litpic/]\" />';\n                @me .= '</div>';\n            }\n            ",0,504);
$z[0][4]=array();
$z[0][4]['runphp']="yes";

?>