<?php
$z[0]=Array("linkurl","",9,25);
$z[0][4]=array();
$z[1]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",44,129);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[2]=Array("imgsrc","",146,161);
$z[2][4]=array();
$z[3]=Array("imgwidth","",175,193);
$z[3][4]=array();
$z[4]=Array("alttext","",199,216);
$z[4][4]=array();
$z[5]=Array("linkurl","",395,411);
$z[5][4]=array();
$z[6]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",413,499);
$z[6][4]=array();
$z[6][4]['runphp']="yes";
$z[7]=Array("alttext","",508,525);
$z[7][4]=array();

?>