<?php
$z[0]=Array("linkurl","",9,25);
$z[0][4]=array();
$z[1]=Array("pagestyle"," @me=(@me==3 ? 'class=\"pic\"' : '' ); ",27,113);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[2]=Array("imgsrc","",130,145);
$z[2][4]=array();
$z[3]=Array("imgwidth","",159,177);
$z[3][4]=array();
$z[4]=Array("alttext","",183,200);
$z[4][4]=array();
$z[5]=Array("linkurl","",238,254);
$z[5][4]=array();
$z[6]=Array("pagestyle","@me=(@me==3 ? 'class=\"title\"' : '' );",256,342);
$z[6][4]=array();
$z[6][4]['runphp']="yes";
$z[7]=Array("title","",349,364);
$z[7][4]=array();

?>