<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/250327/1-155G95V3.jpg ",93,243);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/250327/1-155G95V3.jpg";
$z[1][4]['text']="线稿图";
$z[1][4]['width']="2481";
$z[1][4]['height']="3508";
$z[2]=Array("img"," /uploads/allimg/250327/1-15552VX4.jpg ",245,392);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/250327/1-15552VX4.jpg";
$z[2][4]['text']="铺色";
$z[2][4]['width']="2481";
$z[2][4]['height']="3508";
$z[3]=Array("img"," /uploads/allimg/250327/1-155G94O7.jpg ",394,544);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/250327/1-155G94O7.jpg";
$z[3][4]['text']="上色中";
$z[3][4]['width']="2481";
$z[3][4]['height']="3508";
$z[4]=Array("img"," /uploads/allimg/250327/1-15552MV7.jpg ",546,696);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/250327/1-15552MV7.jpg";
$z[4][4]['text']="最终稿";
$z[4][4]['width']="1920";
$z[4][4]['height']="2715";

?>