{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/250327/1-155G95V3.jpg' text='线稿图' width='2481' height='3508'} /uploads/allimg/250327/1-155G95V3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/250327/1-15552VX4.jpg' text='铺色' width='2481' height='3508'} /uploads/allimg/250327/1-15552VX4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/250327/1-155G94O7.jpg' text='上色中' width='2481' height='3508'} /uploads/allimg/250327/1-155G94O7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/250327/1-15552MV7.jpg' text='最终稿' width='1920' height='2715'} /uploads/allimg/250327/1-15552MV7.jpg {/dede:img}
