<?php
$z[0]=Array("linkurl","",9,25);
$z[0][4]=array();
$z[1]=Array("imgsrc",").'\\\" alt=\\\"'.\$fields['alttext'].'\\\" />' : '<img src=\\\"'.@me.'\\\" alt=\\\"'.\$fields['alttext'].'\\\" />'\"",45,225);
$z[1][4]=array();
$z[1][4]['function']="empty(@me) ? '<img src=\\\"'.GetPicUrl(\$fields['litpic'";
$z[2]=Array("linkurl","",248,264);
$z[2][4]=array();
$z[3]=Array("title","",286,301);
$z[3][4]=array();

?>