<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",103,119);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",121,206);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",236,251);
$z[3][4]=array();
$z[4]=Array("imgwidth","",265,283);
$z[4][4]=array();
$z[5]=Array("alttext","",289,306);
$z[5][4]=array();
$z[6]=Array("linkurl","",368,384);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",386,472);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",491,506);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",544,624);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>