<?php
$z[0]=Array("imgsrc","\n			if(@me == '') {\n				@me = '[field:litpic/]';\n			}\n			",0,99);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",112,128);
$z[1][4]=array();
$z[2]=Array("imgsrc","",157,172);
$z[2][4]=array();
$z[3]=Array("alttext","",179,196);
$z[3][4]=array();
$z[4]=Array("linkurl","",221,237);
$z[4][4]=array();
$z[5]=Array("title","",258,273);
$z[5][4]=array();

?>