<?php
$z[0]=Array("linkurl","",9,25);
$z[0][4]=array();
$z[1]=Array("global","\n					if(empty(\$fields['imgsrc'])) {\n						@me = \"<img src='\".\$fields['litpic'].\"' alt='\".\$fields['alttext'].\"' />\";\n					} else {\n						@me = \"<img src='\".\$fields['imgsrc'].\"' alt='\".\$fields['alttext'].\"' />\";\n					}\n					",45,325);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("linkurl","",348,364);
$z[2][4]=array();
$z[3]=Array("title","",386,401);
$z[3][4]=array();

?>