<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",90,106);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",108,193);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",210,225);
$z[3][4]=array();
$z[4]=Array("imgwidth","",239,257);
$z[4][4]=array();
$z[5]=Array("alttext","",263,280);
$z[5][4]=array();
$z[6]=Array("linkurl","",316,332);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",334,420);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",426,441);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",453,533);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>