<?php
$z[0]=Array("imgsrc","\n          if(@me!='') {\n            @me = '<div class=\"col-7 project-title mobile-full\"><img class=\"image project-header\" src=\"'.@me.'\" id=\"bigimg\"></div>';\n          } else {\n            @me = '<div class=\"col-7 project-title mobile-full\"><img class=\"image project-header\" alt=\"'.@me.'\" src=\"'.@me.'\"></div>';\n          }\n          ",0,376);
$z[0][4]=array();
$z[0][4]['runphp']="yes";

?>