<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",104,120);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",122,207);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",238,253);
$z[3][4]=array();
$z[4]=Array("imgwidth","",267,285);
$z[4][4]=array();
$z[5]=Array("alttext","",291,308);
$z[5][4]=array();
$z[6]=Array("linkurl","",372,388);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",390,476);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",496,511);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",551,631);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>