<?php
$z[0]=Array("arcurl","",131,146);
$z[0][4]=array();
$z[1]=Array("global"," if(@me < 10) { @me = \"0\".@me; } ",254,349);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"\"); ",412,492);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("title","",631,645);
$z[3][4]=array();
$z[4]=Array("litpic","",652,667);
$z[4][4]=array();
$z[5]=Array("pubdate","",795,842);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("title","",881,921);
$z[6][4]=array();
$z[6][4]['function']="cutStr(@me,60)";
$z[7]=Array("description","",959,1006);
$z[7][4]=array();
$z[7][4]['function']="cutStr(@me,120)";

?>