<?php
$z[0]=Array("arcurl","",130,145);
$z[0][4]=array();
$z[1]=Array("global"," if(@me < 10) { @me = \"0\".@me; } ",251,346);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"\"); ",407,487);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("title","",624,638);
$z[3][4]=array();
$z[4]=Array("litpic","",645,660);
$z[4][4]=array();
$z[5]=Array("pubdate","",786,833);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("title","",871,911);
$z[6][4]=array();
$z[6][4]['function']="cutStr(@me,60)";
$z[7]=Array("description","",948,995);
$z[7][4]=array();
$z[7][4]['function']="cutStr(@me,120)";

?>