<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",0,77);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",111,127);
$z[1][4]=array();
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",129,214);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",252,267);
$z[3][4]=array();
$z[4]=Array("imgwidth","",281,299);
$z[4][4]=array();
$z[5]=Array("alttext","",305,322);
$z[5][4]=array();
$z[6]=Array("linkurl","",400,416);
$z[6][4]=array();
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",418,504);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",532,547);
$z[8][4]=array();
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",601,681);
$z[9][4]=array();
$z[9][4]['runphp']="yes";

?>