<?php
$z[0]=Array("global","",50,75);
$z[0][4]=array();
$z[0][4]['name']="cfg_cursor";
$z[1]=Array("global","",308,335);
$z[1][4]=array();
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("channel","\r\n    <a class=\"\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n    ",351,561);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<a class='active' href='~typelink~' ~rel~><span>~typename~</span></a>";

?>